variables:
  GIT_SUBMODULE_STRATEGY: recursive
  THIRD_PARTY_DEPS: /usr/workspace/larsen30/gitlab_runners/third_party_deps/devil_ray
  LLNL_LSF_SCHEDULER_PARAMETERS: "-q pbatch -nnodes 1 -W 60"

build_cuda:
 tags:
   - batch
   - lassen
 stage: build
 script:
   - export DRAY_DIR=$(pwd)
   - ml cmake/3.21.1
   - ml cuda/11.0.2
   - ml gcc/7.3.1
   - mkdir build
   - cd build
   - cmake -C $THIRD_PARTY_DEPS/lassen_cuda.cmake  -DMPIEXEC=jsrun ../src
   - make VERBOSE=1 -j4
   - make test

build_gcc81:
 tags:
   - shell
   - quartz
 stage: build
 script:
   - export DRAY_DIR=$(pwd)
   - ml cmake/3.14.5
   - mkdir build
   - cd build
   - cmake -C $THIRD_PARTY_DEPS/toss3_gcc8_1.cmake  -DMPIEXEC=srun ../src
   - make VERBOSE=1 -j4
   - make test

